config/routes.rb
Rails.application.routes.draw do
  get 'panel/index'

  resources :binnacles
  resources :farming_students
  resources :farmings
  devise_for :users


get "/joincultivo_estudiante/:idusuario/:idcultivo", to: "panel#joincultivo_estudiante"

  authenticated :user do
    devise_scope :user do
      root to: "panel#index", :as => "authenticated"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", :as => "unauthenticated"
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binnacle.rb
class Binnacle < ApplicationRecord
  belongs_to :user
  belongs_to :farming

  has_attached_file :foto1
  validates_attachment_content_type :foto1, content_type: /\Aimage\/.*\z/

  has_attached_file :foto2
  validates_attachment_content_type :foto2, content_type: /\Aimage\/.*\z/

  has_attached_file :foto3
  validates_attachment_content_type :foto3, content_type: /\Aimage\/.*\z/

end

app/models/farming.rb
class Farming < ApplicationRecord
  belongs_to :user
end

app/models/farming_student.rb
class FarmingStudent < ApplicationRecord
  belongs_to :user
  belongs_to :farming
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/binnacles_controller.rb
class BinnaclesController < ApplicationController
  before_action :set_binnacle, only: [:show, :edit, :update, :destroy]


  def index
    if current_user.rol == "profesor"
      @binnacles = Binnacle.all
    else
      @binnacles = Binnacle.where("user_id=?", current_user.id)
    end
  end

  # GET /binnacles/1
  # GET /binnacles/1.json
  def show
  end

  # GET /binnacles/new
  def new
    @binnacle = Binnacle.new
  end

  # GET /binnacles/1/edit
  def edit
  end

  # POST /binnacles
  # POST /binnacles.json
  def create
    @binnacle = Binnacle.new(binnacle_params)

    respond_to do |format|
      if @binnacle.save
        format.html { redirect_to @binnacle, notice: 'Binnacle was successfully created.' }
        format.json { render :show, status: :created, location: @binnacle }
      else
        format.html { render :new }
        format.json { render json: @binnacle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /binnacles/1
  # PATCH/PUT /binnacles/1.json
  def update
    respond_to do |format|
      if @binnacle.update(binnacle_params)
        format.html { redirect_to @binnacle, notice: 'Binnacle was successfully updated.' }
        format.json { render :show, status: :ok, location: @binnacle }
      else
        format.html { render :edit }
        format.json { render json: @binnacle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /binnacles/1
  # DELETE /binnacles/1.json
  def destroy
    @binnacle.destroy
    respond_to do |format|
      format.html { redirect_to binnacles_url, notice: 'Binnacle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_binnacle
      @binnacle = Binnacle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def binnacle_params
      params.require(:binnacle).permit(:user_id, :farming_id, :fecha, :temperatura, :nroriegos, :observaciones, :foto1, :foto2, :foto3)
    end
end

app/controllers/farming_students_controller.rb
class FarmingStudentsController < ApplicationController
  before_action :set_farming_student, only: [:show, :edit, :update, :destroy]

  # GET /farming_students
  # GET /farming_students.json
  def index
    @farming_students = FarmingStudent.all
  end

  # GET /farming_students/1
  # GET /farming_students/1.json
  def show
  end

  # GET /farming_students/new
  def new
    @farming_student = FarmingStudent.new
  end

  # GET /farming_students/1/edit
  def edit
  end

  # POST /farming_students
  # POST /farming_students.json
  def create
    @farming_student = FarmingStudent.new(farming_student_params)

    respond_to do |format|
      if @farming_student.save
        format.html { redirect_to @farming_student, notice: 'Farming student was successfully created.' }
        format.json { render :show, status: :created, location: @farming_student }
      else
        format.html { render :new }
        format.json { render json: @farming_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farming_students/1
  # PATCH/PUT /farming_students/1.json
  def update
    respond_to do |format|
      if @farming_student.update(farming_student_params)
        format.html { redirect_to @farming_student, notice: 'Farming student was successfully updated.' }
        format.json { render :show, status: :ok, location: @farming_student }
      else
        format.html { render :edit }
        format.json { render json: @farming_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farming_students/1
  # DELETE /farming_students/1.json
  def destroy
    @farming_student.destroy
    respond_to do |format|
      format.html { redirect_to farming_students_url, notice: 'Farming student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farming_student
      @farming_student = FarmingStudent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farming_student_params
      params.require(:farming_student).permit(:user_id, :farming_id)
    end
end

app/controllers/farmings_controller.rb
class FarmingsController < ApplicationController
  before_action :set_farming, only: [:show, :edit, :update, :destroy]

  # GET /farmings
  # GET /farmings.json
  def index
    @farmings = Farming.all
  end

  # GET /farmings/1
  # GET /farmings/1.json
  def show
  end

  # GET /farmings/new
  def new
    @farming = Farming.new
  end

  # GET /farmings/1/edit
  def edit
  end

  # POST /farmings
  # POST /farmings.json
  def create
    @farming = Farming.new(farming_params)

    respond_to do |format|
      if @farming.save
        format.html { redirect_to @farming, notice: 'Farming was successfully created.' }
        format.json { render :show, status: :created, location: @farming }
      else
        format.html { render :new }
        format.json { render json: @farming.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farmings/1
  # PATCH/PUT /farmings/1.json
  def update
    respond_to do |format|
      if @farming.update(farming_params)
        format.html { redirect_to @farming, notice: 'Farming was successfully updated.' }
        format.json { render :show, status: :ok, location: @farming }
      else
        format.html { render :edit }
        format.json { render json: @farming.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farmings/1
  # DELETE /farmings/1.json
  def destroy
    @farming.destroy
    respond_to do |format|
      format.html { redirect_to farmings_url, notice: 'Farming was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farming
      @farming = Farming.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farming_params
      params.require(:farming).permit(:user_id, :semilla, :recomendaciones)
    end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
  def index


  end
  def joincultivo_estudiante
    @usuario = params[:idusuario]
    @cultivo = params[:idcultivo]
    @save = FarmingStudent.new(:user_id=>@usuario,:farming_id=>@cultivo)
    @save.save

    @saveuser = User.update(current_user.id, :cultivo=>params[:idcultivo])
    @saveuser.save

    @usermail = User.find(@usuario)
    @teachermail = Farming.find(@cultivo).user
    StudentMailer.addedusertofarming(@usermail).deliver_later
    StudentMailer.addteachertofarming(@teachermail).deliver_later
    redirect_to "/"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binnacles_helper.rb
module BinnaclesHelper
end

app/helpers/farming_students_helper.rb
module FarmingStudentsHelper
end

app/helpers/farmings_helper.rb
module FarmingsHelper
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/views/binnacles/_form.html.erb
<div>
<%= form_with(model: binnacle, local: true) do |form| %>
  <% if binnacle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(binnacle.errors.count, "error") %> prohibited this binnacle from being saved:</h2>

      <ul>
      <% binnacle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="box box-danger">
    <div class="box-header">
    </div>
    <div class="box-body">


    <%= form.hidden_field :user_id, id: :binnacle_user_id, value: current_user.id %>
    <%= form.hidden_field :farming_id, id: :binnacle_farming_id, value: current_user.cultivo %>


  <div class="row" >

    <div class="col-md-8">
      <label>Fecha</label>
       <%= form.text_field :fecha, id: :binnacle_fecha, class: "form-control", value:Time.now.strftime("%F") %>
      </div>
  </div>

<div class="row" >

    <div class="col-md-8">
      <label>Temperatura</label>
       <%= form.text_field :temperatura, id: :binnacle_temperatura, class: "form-control" %>
      </div>
</div>

<div class="row" >

    <div class="col-md-8">
      <label>Número de Riegos</label>
        <%= form.text_field :nroriegos, id: :binnacle_nroriegos, class: "form-control"%>
      </div>
</div>

<div class="row" >

    <div class="col-md-8">
      <label>Observaciones</label>
        <%= form.text_area :observaciones, id: :binnacle_observaciones, class: "form-control"%>
      </div>
</div>

<div class="row" >

    <div class="col-md-8">
      <label>Foto 1</label>
        <%= form.file_field :foto1, id: :binnacle_foto1, class: "form-control"%>
      </div>
</div>

<div class="row" >

    <div class="col-md-8">
      <label>Foto 2</label>
        <%= form.file_field :foto2, id: :binnacle_foto2, class: "form-control"%>
      </div>
</div>

<div class="row" >

    <div class="col-md-8">
      <label>Foto 3</label>
        <%= form.file_field :foto3, id: :binnacle_foto3,  class: "form-control"%>
      </div>
</div>

<br>
  <div class="actions">
    <%= form.submit "Enviar" ,class:"btn btn-primary" %>
  </div>

<% end %>
</div><!-- /.form group -->
</div>


<script>
function gettingJSON(){
    $.getJSON("http://api.openweathermap.org/data/2.5/weather?lat=6.25&lon=-75.56&APPID=24705a0916896d12b44e849327037eaf",function(json){
        document.getElementById("binnacle_temperatura").value = (json.main.temp/10).toFixed(2)+"°";
    });
}
window.onload = gettingJSON;
</script>

app/views/binnacles/edit.html.erb
<h1>Editing Binnacle</h1>

<%= render 'form', binnacle: @binnacle %>

<%= link_to 'Show', @binnacle %> |
<%= link_to 'Back', binnacles_path %>

app/views/binnacles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bienvenidos a su Bitacora</h1>
<%= link_to 'Nueva Bitacora', new_binnacle_path, class:"btn btn-primary" %><br>

                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Tabla de Datos con el Registro de su Actividad</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Cultivo</th>
                                                <th>Fecha</th>
                                                <th>Temperatura</th>
                                                <th>Número de Riegos</th>
                                                <th>Foto 1</th>
                                                <th>Foto 2</th>
                                                <th>Foto 3</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                          <% @binnacles.each do |bs| %>
                                            <tr>
                                                <th><%= bs.farming.semilla %></th>
                                                <th><%= bs.fecha %></th>
                                                <th><%= bs.temperatura %></th>
                                                <th><%= bs.nroriegos %></th>
                                                <th><img src="<%= bs.foto1 %>" style="width:80px" alt=""></th>
                                                <th><img src="<%= bs.foto2 %>" style="width:80px" alt=""></th>
                                                <th><img src="<%= bs.foto3 %>" style="width:80px" alt=""></th>
                                            </tr>
                                          <%end%>

                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
<br>

<script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
                $('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
        </script>

app/views/binnacles/new.html.erb
<h1>Nueva Bitacora</h1>


<%= render 'form', binnacle: @binnacle %>

<%= link_to 'Back', binnacles_path %>

app/views/binnacles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @binnacle.user %>
</p>

<p>
  <strong>Farming:</strong>
  <%= @binnacle.farming %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @binnacle.fecha %>
</p>

<p>
  <strong>Temperatura:</strong>
  <%= @binnacle.temperatura %>
</p>

<p>
  <strong>Nroriegos:</strong>
  <%= @binnacle.nroriegos %>
</p>

<p>
  <strong>Observaciones:</strong>
  <%= @binnacle.observaciones %>
</p>

<p>
  <strong>Foto1:</strong>
  <%= @binnacle.foto1 %>
</p>

<p>
  <strong>Foto2:</strong>
  <%= @binnacle.foto2 %>
</p>

<p>
  <strong>Foto3:</strong>
  <%= @binnacle.foto3 %>
</p>

<%= link_to 'Edit', edit_binnacle_path(@binnacle) %> |
<%= link_to 'Back', binnacles_path %>

app/views/farming_students/_form.html.erb
<html>

<style>
  

       body{
            
            margin-bottom: 10px;  

       }

      .field{

          margin-bottom: 25px;
          text-align: center;
          width: 50%;
          height: 100%;

          

      }
      
      .row1{
        padding: 5px;
      }


</style>



<body>
  

  <div class="row">
  <div class="col-md-12 col-md-offset-3">

  <%= form_with(model: farming_student, local: true) do |form| %>
    <% if farming_student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(farming_student.errors.count, "error") %> prohibited this farming_student from being saved:</h2>

        <ul>
        <% farming_student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :user_id %>
      <%= form.text_field :user_id, id: :farming_student_user_id, class: "form-control"%>
    </div>

    <div class="field">
      <%= form.label :farming_id %>
      <%= form.text_field :farming_id, id: :farming_student_farming_id, class: "form-control"%>
    </div>

    

</div>
    </div>

<div class="row1">
  <div class="col-md-6 col-md-offset-3">

<div class="actions">
      <%= form.submit style: "border-radius: 10px; color: black; text-align: center; padding: 7px; border: none;
 background: #3a7999;
 color: #f2f2f2;
 padding: 10px;
 font-size: 18px;
 border-radius: 5px;
 position: relative;
 box-sizing: border-box;
 transition: all 500ms ease;
"%>

</div>

<%= link_to 'Back', farming_students_path%>
</div>
</div>

  <% end %>

  </body>

</html>

app/views/farming_students/edit.html.erb
<h1>Editando cultivo de estudiante</h1>

<%= render 'form', farming_student: @farming_student %>

<%= link_to 'Show', @farming_student %> |
<%= link_to 'Back', farming_students_path%>

app/views/farming_students/index.html.erb
<p id="notice"><%= notice %></p>




  <h1>Cultivos de estudiantes</h1>


<div class = "table">

 <table id="example1" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Usuario</th>
        <th>Cultivo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

   
  </table>

</div>
  <%= link_to 'Nuevo Cultivo', new_farming_student_path %>


<script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
                $('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
        </script>

app/views/farming_students/new.html.erb
<html>

    
    <style>

          body{
              
              text-align: center;
              font-family: arial;
              font-size: 12px;
              margin-bottom: 10px;
              
               
          }


          
    </style>



   <body>
   	
		<h1>Nuevo cultivo de estudiante</h1>


		<%= render 'form' ,farming_student: @farming_student%>

		

	</body>

</html>

app/views/farming_students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @farming_student.user %>
</p>

<p>
  <strong>Farming:</strong>
  <%= @farming_student.farming %>
</p>

<%= link_to 'Edit', edit_farming_student_path(@farming_student) %> |
<%= link_to 'Back', farming_students_path %>

app/views/farmings/_form.html.erb
<%= form_with(model: farming, local: true) do |form| %>
  <% if farming.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(farming.errors.count, "error") %> prohibited this farming from being saved:</h2>

      <ul>
      <% farming.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :farming_user_id %>
  </div>

  <div class="field">
    <%= form.label :semilla %>
    <%= form.text_field :semilla, id: :farming_semilla %>
  </div>

  <div class="field">
    <%= form.label :recomendaciones %>
    <%= form.text_area :recomendaciones, id: :farming_recomendaciones %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/farmings/edit.html.erb
<h1>Editing Farming</h1>

<%= render 'form', farming: @farming %>

<%= link_to 'Show', @farming %> |
<%= link_to 'Back', farmings_path %>

app/views/farmings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Farmings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Semilla</th>
      <th>Recomendaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @farmings.each do |farming| %>
      <tr>
        <td><%= farming.user %></td>
        <td><%= farming.semilla %></td>
        <td><%= farming.recomendaciones %></td>
        <td><%= link_to 'Show', farming %></td>
        <td><%= link_to 'Edit', edit_farming_path(farming) %></td>
        <td><%= link_to 'Destroy', farming, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Farming', new_farming_path %>

app/views/farmings/new.html.erb
<h1>New Farming</h1>

<%= render 'form', farming: @farming %>

<%= link_to 'Back', farmings_path %>

app/views/farmings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @farming.user %>
</p>

<p>
  <strong>Semilla:</strong>
  <%= @farming.semilla %>
</p>

<p>
  <strong>Recomendaciones:</strong>
  <%= @farming.recomendaciones %>
</p>

<%= link_to 'Edit', edit_farming_path(@farming) %> |
<%= link_to 'Back', farmings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controlcultivo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
  </head>

  <body>
    <% if user_signed_in? %>
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/panel/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/panel/css/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/panel/css/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="/panel/css/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/panel/css/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="/panel/css/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/panel/css/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="/panel/css/bootstrap3-wysihtml5.min.css">
     <link rel="stylesheet" href="/panel/css/_all.css">
     <link rel="stylesheet" href="/panel/css/green.css">
     <link rel="stylesheet" href="/panel/css/red.css">
      <link href="/panel/css/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />

      <%= render 'layouts/menupanel' %>

  <!-- jQuery UI 1.11.4 -->
  
  <script src="/panel/js/bootstrap.js"></script>
  <!-- Morris.js charts -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <script src="/panel/js/morris.min.js"></script>
  <!-- Sparkline -->
  <script src="/panel/js/jquery.sparkline.min.js"></script>
  <!-- jvectormap -->
  <script src="/panel/js/jquery-jvectormap-1.2.2.min.js"></script>
  <script src="/panel/js/jquery-jvectormap-world-mill-en.js"></script>
  <!-- jQuery Knob Chart -->
  <script src="/panel/js/jquery.knob.js"></script>
  <!-- daterangepicker -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
  <script src="/panel/js/daterangepicker.js"></script>
  <!-- datepicker -->
  <script src="/panel/js/bootstrap-datepicker.js"></script>
  <!-- Bootstrap WYSIHTML5 -->
  <script src="/panel/js/bootstrap3-wysihtml5.all.min.js"></script>
  <!-- Slimscroll -->
  <script src="/panel/js/jquery.slimscroll.min.js"></script>
  <!-- FastClick -->
  <script src="/panel/js/fastclick.js"></script>
  <script src="/panel/js/jquery.dataTables.js" type="text/javascript"></script>
  <script src="/panel/js/dataTables.bootstrap.js" type="text/javascript"></script>
  <!-- AdminLTE App -->
  <script src="/panel/js/app.min.js"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="/panel/js/dashboard.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/panel/js/demo.js"></script>



<%else%>
    <%= yield %>
  <%end%>

  </body>
</html>